hugoblox:
  schema: "2.0"
  identity:
    name: Tomeu López-Nieto Veitch
    type: person
    tagline: PhD Candidate in Statistics | Università di Bologna
    description: ""
    organization: Università di Bologna
  theme:
    mode: system
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: "neutral"
    colors_light:
      primary: ""
      secondary: ""
      neutral: ""
    surfaces:
      header: {}
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: square
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
    license:
      share_alike: false
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
